version: "3.7"

services:
  app:
    image: buidler/buidler-webapp:latest
    build:
      context: ..
      dockerfile: Dockerfile
    expose:
      - "80"
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=community.buidler.app
      - VIRTUAL_PORT=80
      # - LETSENCRYPT_HOST=community.buidler.app
      # - LETSENCRYPT_EMAIL="test.tai.htm@gmail.com"
networks: 
  default:  
    name: nginx-proxy
    external: true