const EventName = {
  ON_NEW_MESSAGE: "ON_NEW_MESSAGE",
  ON_DELETE_MESSAGE: "ON_DELETE_MESSAGE",
  ON_EDIT_MESSAGE: "ON_EDIT_MESSAGE",
  ON_REACTION_ADDED: "ON_REACTION_ADDED",
  ON_REACTION_REMOVED: "ON_REACTION_REMOVED",
  ON_CREATE_NEW_COMMUNITY: "ON_CREATE_NEW_COMMUNITY",
  ON_USER_JOIN_COMMUNITY: "ON_USER_JOIN_COMMUNITY",
};

export default EventName;
