const EventName = {
  ON_NEW_MESSAGE: "ON_NEW_MESSAGE",
  ON_DELETE_MESSAGE: "ON_DELETE_MESSAGE",
  ON_EDIT_MESSAGE: "ON_EDIT_MESSAGE",
  ON_REACTION_ADDED: "ON_NEW_REACTION",
  ON_REACTION_REMOVED: "ON_DELETE_REACTION",
  ON_CREATE_NEW_COMMUNITY: "ON_CREATE_NEW_COMMUNITY",
  ON_USER_JOIN_COMMUNITY: "ON_USER_JOIN_COMMUNITY",
  ON_USER_JOIN_CHANNEL: "ON_USER_JOIN_CHANNEL",
  ON_USER_LEAVE_CHANNEL: "ON_USER_LEAVE_CHANNEL",
  ON_NEW_TOPIC: "ON_NEW_TOPIC",
  ON_USER_UPDATE_PROFILE: "ON_USER_UPDATE_PROFILE",
  ON_NEW_COMMENT: "ON_NEW_COMMENT",
  ON_UPDATE_TOTAL_ONLINE_USERS: "ON_UPDATE_TOTAL_ONLINE_USERS",
  GET_TOTAL_ONLINE_USERS: "GET_TOTAL_ONLINE_USERS",
};

export default EventName;
