namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_API_BASE_URL: string;
    NEXT_PUBLIC_DEFAULT_CHAIN_ID: string;
    NEXT_PUBLIC_MIXPANEL_TOKEN: string;
    NEXT_PUBLIC_ENABLE_INSPECT: string;
    NEXT_PUBLIC_IMAGE_KEY: string;
    NEXT_PUBLIC_IMAGE_SALT: string;
    NEXT_PUBLIC_FIREBASE_API_KEY: string;
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: string;
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: string;
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: string;
    NEXT_PUBLIC_FIREBASE_APP_ID: string;
    NEXT_PUBLIC_WEB3_AUTH_CLIENT_ID: string;
    NEXT_PUBLIC_PROFILE_URL: string;
    NEXT_PUBLIC_URL: string;
  }
}
